#!/usr/bin/env python3
"""Generate the Homebrew formula for nearai/homebrew-tap.

A binary formula: it downloads the release archive for the user's platform and
verifies the sha256 that this script reads out of the actual artifacts. Nothing
is compiled, and the checksums are never typed by a human.

The formula also installs shell completions and a `brew services` definition, so
`brew services start ironwire` works — which is how a macOS user expects to run
a background daemon.

Run locally:
    python packaging/build_brew.py --version 0.1.0 --dist <dir> --out ironwire.rb
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

REPO = "nearai/ironwire"

PLATFORMS = [
    ("aarch64-apple-darwin", "on_macos", "Hardware::CPU.arm?"),
    ("x86_64-apple-darwin", "on_macos", "Hardware::CPU.intel?"),
    ("aarch64-unknown-linux-gnu", "on_linux", "Hardware::CPU.arm?"),
    ("x86_64-unknown-linux-gnu", "on_linux", "Hardware::CPU.intel?"),
]

TEMPLATE = '''# Generated by packaging/build_brew.py — do not edit.
class Ironwire < Formula
  desc "Localhost router for coding agents"
  homepage "https://github.com/{repo}"
  version "{version}"
  license any_of: ["MIT", "Apache-2.0"]

{blocks}
  def install
    bin.install "ironwire"
    generate_completions_from_executable(bin/"ironwire", "completions", shells: [:bash, :zsh, :fish])
  end

  # A user agent, not a system daemon. IronWire reads the OAuth tokens Claude
  # Code and Codex stored in this user's home directory and binds 127.0.0.1
  # only; running it as root would be a category error.
  service do
    run [opt_bin/"ironwire", "serve"]
    keep_alive true
    working_dir Dir.home
    log_path var/"log/ironwire.log"
    error_log_path var/"log/ironwire.log"
  end

  def caveats
    <<~EOS
      IronWire binds 127.0.0.1 only and keeps its state in ~/.ironwire.
      No subscription is used until you enable it explicitly.

      Point your agent at it:
        ironwire connect claude
        ironwire connect codex

      Run it:
        ironwire serve                  in the foreground
        brew services start ironwire    in the background
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/ironwire --version")
    # `doctor` must work with nothing configured — it is the first thing a
    # confused user runs, and it exits non-zero when nothing is connected.
    shell_output("#{{bin}}/ironwire doctor 2>&1", 1)
  end
end
'''


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--dist", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    base = f"https://github.com/{REPO}/releases/download/v{args.version}"

    by_os: dict[str, list[str]] = {"on_macos": [], "on_linux": []}
    for target, os_block, cpu in PLATFORMS:
        archive = args.dist / f"ironwire-{target}.tar.gz"
        if not archive.exists():
            print(f"warning: no artifact for {target}; omitting from formula")
            continue
        by_os[os_block].append(
            f"    {'if' if not by_os[os_block] else 'elsif'} {cpu}\n"
            f'      url "{base}/ironwire-{target}.tar.gz"\n'
            f'      sha256 "{sha256(archive)}"\n'
        )

    blocks = ""
    for os_block, entries in by_os.items():
        if not entries:
            continue
        blocks += f"  {os_block} do\n" + "".join(entries) + "    end\n  end\n\n"

    if not blocks:
        raise SystemExit("no artifacts found — refusing to write an empty formula")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(TEMPLATE.format(repo=REPO, version=args.version, blocks=blocks))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
