#!/usr/bin/env node
// Build the npm packages from the release artifacts.
//
// One thin `ironwire` package plus a per-platform `@ironwire/cli-<os>-<arch>`
// package listed as an optional dependency. npm's `os`/`cpu` fields mean a
// user only downloads the binary for the machine they are on — a
// `npx ironwire@latest` therefore costs one ~7 MB download, not six.
//
// No postinstall script. A postinstall that downloads is the thing that breaks
// behind corporate proxies, in offline CI, and under `npm ci --ignore-scripts`,
// and it is also how supply-chain attacks get their foothold. The binary is
// *in* the package; the shim just execs it.
//
// Run locally:  node packaging/build_npm.mjs --version 0.1.0 \
//                   --artifacts <dir> --out npm-dist

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const TARGETS = [
  { target: 'aarch64-apple-darwin',      os: 'darwin', cpu: 'arm64', ext: '.tar.gz' },
  { target: 'x86_64-apple-darwin',       os: 'darwin', cpu: 'x64',   ext: '.tar.gz' },
  { target: 'x86_64-unknown-linux-gnu',  os: 'linux',  cpu: 'x64',   ext: '.tar.gz' },
  { target: 'aarch64-unknown-linux-gnu', os: 'linux',  cpu: 'arm64', ext: '.tar.gz' },
  { target: 'x86_64-pc-windows-msvc',    os: 'win32',  cpu: 'x64',   ext: '.zip' },
];

const REPO = 'https://github.com/nearai/ironwire';

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  if (i !== -1 && process.argv[i + 1]) return process.argv[i + 1];
  if (fallback !== undefined) return fallback;
  throw new Error(`missing --${name}`);
}

const version = arg('version');
const artifacts = arg('artifacts');
const out = arg('out', 'npm-dist');

const common = {
  version,
  license: 'MIT OR Apache-2.0',
  homepage: `${REPO}#readme`,
  repository: { type: 'git', url: `git+${REPO}.git` },
  publishConfig: { access: 'public' },
};

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

// ---------------------------------------------------------- platform packages

const optionalDependencies = {};
const built = [];

for (const t of TARGETS) {
  const archive = path.join(artifacts, `ironwire-${t.target}${t.ext}`);
  if (!fs.existsSync(archive)) {
    // A missing target is a real gap in the release, not something to paper
    // over: the user on that platform would get a confusing npm error instead
    // of a clear one. Say it loudly and keep going so the rest still ships.
    console.warn(`warning: no artifact for ${t.target}; skipping`);
    continue;
  }

  const name = `@ironwire/cli-${t.os}-${t.cpu}`;
  const dir = path.join(out, `cli-${t.os}-${t.cpu}`);
  const binName = t.os === 'win32' ? 'ironwire.exe' : 'ironwire';
  fs.mkdirSync(path.join(dir, 'bin'), { recursive: true });

  if (t.ext === '.zip') {
    execFileSync('unzip', ['-o', '-q', archive, '-d', path.join(dir, 'bin')]);
  } else {
    execFileSync('tar', ['-xzf', archive, '-C', path.join(dir, 'bin')]);
  }
  fs.chmodSync(path.join(dir, 'bin', binName), 0o755);

  fs.writeFileSync(
    path.join(dir, 'package.json'),
    JSON.stringify(
      {
        name,
        ...common,
        description: `IronWire binary for ${t.os}-${t.cpu}`,
        os: [t.os],
        cpu: [t.cpu],
        files: ['bin/'],
      },
      null,
      2,
    ) + '\n',
  );

  optionalDependencies[name] = version;
  built.push(name);
}

if (built.length === 0) throw new Error('no platform artifacts found — nothing to publish');

// ------------------------------------------------------------- shim package

const shimDir = path.join(out, 'ironwire');
fs.mkdirSync(path.join(shimDir, 'bin'), { recursive: true });

fs.writeFileSync(
  path.join(shimDir, 'package.json'),
  JSON.stringify(
    {
      name: 'ironwire',
      ...common,
      description:
        'Localhost router for coding agents — aggregate the subscriptions, keys and credits you already have',
      keywords: ['claude', 'codex', 'aider', 'llm', 'proxy', 'router', 'openrouter'],
      bin: { ironwire: 'bin/ironwire.js' },
      files: ['bin/'],
      optionalDependencies,
      engines: { node: '>=18' },
    },
    null,
    2,
  ) + '\n',
);

// The shim resolves the platform package and execs it, replacing this process
// where the OS allows. Signals, exit codes and TTY behaviour then belong to the
// real binary — which matters, because `ironwire serve` is a long-running
// foreground process people stop with Ctrl-C.
fs.writeFileSync(
  path.join(shimDir, 'bin', 'ironwire.js'),
  `#!/usr/bin/env node
// Generated by packaging/build_npm.mjs — do not edit.
import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const platform = \`\${process.platform}-\${process.arch}\`;
const binary = process.platform === 'win32' ? 'ironwire.exe' : 'ironwire';

let resolved;
try {
  resolved = require.resolve(\`@ironwire/cli-\${platform}/bin/\${binary}\`);
} catch {
  console.error(\`ironwire: no prebuilt binary for \${platform}.\`);
  console.error('');
  console.error('Supported: darwin-arm64, darwin-x64, linux-x64, linux-arm64, win32-x64');
  console.error('Build from source:  cargo install --git ${REPO}');
  console.error('');
  console.error("If your platform is in that list, the optional dependency may have been");
  console.error('skipped — try:  npm install --include=optional ironwire');
  process.exit(1);
}

const result = spawnSync(resolved, process.argv.slice(2), { stdio: 'inherit' });
if (result.error) {
  console.error(\`ironwire: could not run \${resolved}: \${result.error.message}\`);
  process.exit(1);
}
// Preserve signal deaths as a shell would report them, so Ctrl-C on
// \`npx ironwire serve\` behaves the way the user expects.
if (result.signal) process.exit(128 + (require('node:os').constants.signals[result.signal] ?? 0));
process.exit(result.status ?? 0);
`,
);
fs.chmodSync(path.join(shimDir, 'bin', 'ironwire.js'), 0o755);

for (const f of ['README.md', 'LICENSE-MIT', 'LICENSE-APACHE']) {
  if (fs.existsSync(f)) fs.copyFileSync(f, path.join(shimDir, path.basename(f)));
}

console.log(`built ${built.length + 1} packages in ${out}/`);
for (const name of [...built, 'ironwire']) console.log(`  ${name}@${version}`);
